version: "3.9"
services:
  database:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      -   "3330:5432"
    environment:
      POSTGRES_DB: restRecipesDB
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: lekkereten
    volumes:
      - recipes-db-config:/etc/postgres
      - recipes-db:/var/lib/postgresql/data
  rest-api:
    depends_on: [database]
    build: .
    ports:
      - "8000:8000"
volumes:
  recipes-db-config:
  recipes-db: